### PR TITLE
feat: boilerplate collect command

### PR DESCRIPTION
**Pull request by hacdias**
See #376.

License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

### CODE REVIEW

**Comment by nonsense** [comment]
@hacdias @raulk this is a tricky one when the `artifacts/assets` are on S3, because we can't zip them directly on S3. We could add a CloudFront service in front of S3, which could serve gzip responses (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html)

**Comment by nonsense** [comment]
Related: https://github.com/ipfs/testground/pull/440

**Comment by hacdias** [comment]
In the meanwhile, I think this is ready for merging. We could implement each function for each runner on separate PRs.

**Comment by raulk** [comment]
The code herein became the starting point for https://github.com/ipfs/testground/pull/463, which is the PR that will land. Closing this one in favour of that.

**Pull request closed without merging**
