### PR TITLE
Add a state machine

### PR DESCRIPTION
**Pull request by coryschwartz**
The purpose for this is to abstract away synchronization methods and allow modeling for patterns, such as plan factories.

### CODE REVIEW

**Comment by Stebalien** [comment]
Can we get an example of this in practice?

**Comment by coryschwartz** [comment]
@Stebalien I added an example for you.

I admit it's a bit hard to read, but the idea I'm shooting for is to be able to abstract away some of the details, like barriers between phases of a test.

It seems to me that many of the tests are written in distinct phases, acts, whatever. The example would allow multiple acts to be performed with a barrier between them. The whole test plan is constructed using a factory. 

The factory, in my mind, could be managed by in the SDK and used by plans. We would add factories for common patterns, barrier configurations, etc.


It might be easier just to copy frequently used methods into a 'utils' package. I could imagine just copying methods from the bitswap-tuning and others that plans that have made good utils.

**Comment by Stebalien** [comment]
I guess, at this point, I'm not seeing how this could be used to simplify the tests. It's probably more flexible (and simpler) to just write:

```go
var err error
for i, stage := []func(...){
  Stage1, // defined elsewhere.
  Stage2,
  Stage3,
} {
    if err == nil { // we still want to hit the barriers if we hit a failure.
        err = stage(...)
    }
    BarrierHelper(fmt.Sprintf("barrier-%d", i))
}
teardown(...)
return err
```

We could even put this in a function if it becomes a pattern.

**Comment by coryschwartz** [comment]
True, and not merging.

I was going for re-usable patterns similar to operators in apache airflow, but I have to agree with you I'm not happy with this change. Closing.

**Comment by Robmat05** [comment]
ok, this ticket has been abandoned and will be closed and tagged as ‘Rotten’

**Pull request closed without merging**
