### PR TITLE
Infra Lead Responsibilities Handoff.initiate()

### PR DESCRIPTION
**Pull request by daviddias**
@nonsense, just came out of a chat with @jimpick and we found that now that you have been onboarded to the project and are tacking more and more responsibility in how TestGround provides a complete Service to the team, it makes sense (as it was planned) for you to also own the work that @jimpick has valiantly championed for us, getting us with a Cluster that we can use, even though it was not is bread and butter.

@jimpick will more focused on develping Test Plans, starting with #96 and then expanding his scope to think about developer experience, onboarding (docs, demos) and overall, making sure we make writing Test Plans super simple and fun.

For a good handoff, @jimpick please write down a brain dump of:
- Where Infra is today
- Where it needs to be
- What are still some of the open questions
- What are things we have decided not to build
- Other considerations that @nonsense should no

Then, ensure that @nonsense has access to all the admin panels (AWS, Elastic Search, etc).

Once this is written down, I propose that @jimpick and @nonsense have a __recorded__ Zoom call in which you go through all of it, with @nonsense following and asking question + replicating the steps, similar to the walk through from @raulk back in September. Once that is done, share it with the team so that we all can learn as well.

### CODE REVIEW

**Comment by jimpick** [comment]
Sounds good to me.

Super quick brain dump:

# Where Infra is today

  - There is an AWS account (intentionally bare, just some IAM accounts for people with access)
  - I set up the smallest possible ElasticSearch/Kibana cluster using Elastic.co ... billed via AWS Marketplace
 - There automation for quickly creating clusters under /infra in the source code
   - /infra/packer to build the base AMI image
   - /infra/terraform to automated provisioning EC2 resources
   - /infra/ansible to perform post-provisioning cluster setup steps (Docker Swarm, Filebeat, ssh keys)

# Where it needs to be

 - It's pretty easy to set up a cluster from scratch now
 - Nice to haves:
    - fully automated setup from the Terraform script (have it call Ansible)
    - setup team member ssh keys #186 

# What are still some of the open questions

- how many clusters are we going to use?
- do we share clusters between users?
- what is the configuration of the cluster(s) for use from CI?
- future tests may need to use additional AWS functionality ... eg. EBS snapshots

# What are things we have decided not to build

- in the beginning, we decided to not implement fine-grained permissions and roles ... in order to get people going quickly, everybody with an IAM account has full access

# Other considerations

- I think the level of automation is satisfying ... it's hard to predict what extra is needed until the AWS infrastructure is being actively used. It has only been used as a testground development target so far.

**Comment by nonsense** [comment]
I agree with everything said so far. I am mostly aware of where we are at with infra, as I have been reviewing playbooks (terraform and ansible) over the last few days. I suggest I allocate a bit of time to review them more carefully, and then we do a Zoom call and handover with @jimpick

**Comment by daviddias** [comment]
Thank you @jimpick, @nonsense. I'm merging this PR then :) 

Please share the recording when you get it done. Cheers!

**Comment by nonsense** [comment]
We had a great chat with @jimpick and went over the Ansible and Terraform playbooks and the READMEs and the ElasticSearch setup.

The current state of infrastructure playbooks are at https://github.com/ipfs/testground/pull/210 with the README being up-to-date.

There are a few known issues as well as things we should continue to iterate on (for example setting up the `terraform daemon` remotely, etc.), but ultimately we are making good progress.

**Pull request merged**
