### PR TITLE
Create a Roadmap for TestGround

### PR DESCRIPTION
**Pull request by daviddias**
As requested by the IPFS Project Lead, @momack2 :) 🚀 💎 

The Roadmap as it stands is kind of redundant to the OKRs for Q4. It might prove to become a good instrument for planning for multiple quarters at a time when 2020 plans are made.

@raulk I would love your review first as the Tech Lead / Architect for the project, so that then others can review.

### CODE REVIEW

**Comment by momack2** [comment]
Hey David. just food for thought, but I was thinking something more along the lines of this tracker: https://docs.google.com/spreadsheets/d/1xyqyGUF-oe3x9ln88YonVeOMWWdknik74lVgL_3dBY8/edit#gid=0 in the way it details work to be done, owners, relative ordering, and delivery milestones.

**Comment by daviddias** [comment]
@momack2 we could use Trello for creating that view into the work, right?

**Comment by daviddias** [comment]
Zenhub just launched an integrated Roadmap feature that is worth looking at for this https://techcrunch.com/2019/11/05/zenhub-adds-roadmapping-to-its-github-project-management-tool/

**Comment by momack2** [comment]
The info encoded in the zenhub roadmap -- "we're going to complete X testplan by Y time // we're going to support Z feature to unblock X testplan 2 weeks in advance of launch" is what I'm looking for here, so that could work! As you see in the tracker - milestones with due dates and rough time estimates can be useful planning tools (better when they aren't out of date though... ;)

**Comment by daviddias** [comment]
Still playing with it to make up my mind on how to best use Zenhub to organize this information.

The Roadmap feature is indeed interesting 
image

**Comment by daviddias** [comment]
Updated the ROADMAP doc to link to the functional ROADMAP and the MVP Goal issue. Will merge as is and revisit in 2020.

**Pull request merged**
