### PR TITLE
Add bitswap test suite

### PR DESCRIPTION
**Pull request by dirkmc**
This PR contains test suites that
- run testground with several combinations of seeds and leeches, measuring the performance (time to fetch, duplicate blocks) at different latency / bandwidth for varying file size.
  Results: https://github.com/ipfs/go-ipfs/issues/6782
- run testground with 1 leech / 3 seeds (100ms / 500ms / 1000ms latency) to test that Bitswap favours lower latency seeds.
  Results: https://github.com/ipfs/testground/issues/436

### CODE REVIEW

**Comment by Stebalien** [comment]
@dirkmc we can probably rebase and land this, right?

**Comment by dirkmc** [comment]
Yes, it's just been waiting for review - I will rebase and ping you

**Comment by dirkmc** [comment]
@Stebalien I rebased so this is now mergeable - I have another branch that depends on this one that also cleans up some of the code, so if there's nothing major I'd suggest we merge and then refactor

**Comment by Stebalien** [comment]
Yeah, this PR just touches the test plan so I'm not concerned about potential issues.

**Comment by Stebalien** [comment]
I fixed the lints to get CI passing.

**Pull request merged**
