### PR TITLE
Improve test output. No more false positives on CI

### PR DESCRIPTION
**Pull request by Stebalien**
* Pretty print
* Return a non-zero exit code on failure (fixes CI).
* Fix the find peers test

### CODE REVIEW

**Comment by Stebalien** [comment]
Note: this does not add metrics _summaries_. I figured we should do that in a followup to keep this one manageable.

Please review commit by commit.

**Comment by daviddias** [comment]
@Stebalien can't tell if this PR is ready for Review & Merge or if you are still working on it. Mixed signals are::
- PR is tagged as "ready to review" (Suggests that you want a review)
- CI is red (Suggests that is still not ready to review)
- It's on the "New issues" column on ZenHub (Suggests that is still not ready to review)

**Comment by Stebalien** [comment]
> CI is red (Suggests that is still not ready to review)

The tests have never passed. We just weren't returning the error. If you take a look at any CI run, you'll see:

```
<< instance 1 >> {"runenv":{"test_plan":"dht","test_case":"find-peers","test_run":"7ba680be-7dca-46c7-85f2-3727a10d2ec6","test_seq":0,"test_instance_count":5,"test_instance_params":{"timeout_secs":"15"}},"timestamp":1575304232176878658,"result":{"outcome":"aborted","reason":"context deadline exceeded; not enough elements, required: 5, got: 1"}}

<< instance 0 >> {"runenv":{"test_plan":"dht","test_case":"find-peers","test_run":"7ba680be-7dca-46c7-85f2-3727a10d2ec6","test_seq":0,"test_instance_count":5,"test_instance_params":{"timeout_secs":"15"}},"timestamp":1575304233022089560,"result":{"outcome":"aborted","reason":"no new peers in 15 seconds"}}

<< instance 2 >> {"runenv":{"test_plan":"dht","test_case":"find-peers","test_run":"7ba680be-7dca-46c7-85f2-3727a10d2ec6","test_seq":0,"test_instance_count":5,"test_instance_params":{"timeout_secs":"15"}},"timestamp":1575304233103181431,"result":{"outcome":"aborted","reason":"no new peers in 15 seconds"}}

<< instance 3 >> {"runenv":{"test_plan":"dht","test_case":"find-peers","test_run":"7ba680be-7dca-46c7-85f2-3727a10d2ec6","test_seq":0,"test_instance_count":5,"test_instance_params":{"timeout_secs":"15"}},"timestamp":1575304233258770964,"result":{"outcome":"aborted","reason":"no new peers in 15 seconds"}}

<< instance 4 >> {"runenv":{"test_plan":"dht","test_case":"find-peers","test_run":"7ba680be-7dca-46c7-85f2-3727a10d2ec6","test_seq":0,"test_instance_count":5,"test_instance_params":{"timeout_secs":"15"}},"timestamp":1575304233334620243,"result":{"outcome":"aborted","reason":"no new peers in 15 seconds"}}

{"runnerId":""}

The command "./testground -vv run dht/find-peers --builder=exec:go --runner=local:exec --test-param timeout_secs=15" exited with 0.
```

Let's block this on https://github.com/ipfs/testground/pull/179. I'm going to need to work on the tests in order to get CI to pass.

**Comment by hacdias** [comment]
Please merge this into **demo** but note this **does not return a non-zero code** due to the changes made to the server logic in the meanwhile. I'll make another PR with those fixes.

**Pull request merged**
